core/urls.py
from django.urls import path
from .views import *


app_name = 'core'
urlpatterns = [
    path('', index, name='index'),
    path('categorias/', categories, name='categories'),
    path('categoria/<slug:slug>/', category_product, name='category_product'),
    path('produto/<slug:slug>/', product, name='product'),

    path('favorito-<int:id>/', favorite, name='favorite'),
    path('favoritos/', favorites, name='favorites'),
    
    path('carrinho-<int:id>/', cart, name='cart'),
    path('meu-carrinho/', my_cart, name='my_cart'),
    path('editar-carrinho/<int:id>/', edit_cart, name='edit_cart'),
    path('remover-carrinho/', remove_cart, name='remove_cart'),
    path('comprar/', buy, name='buy'),
    path('entregar/', delivery, name='delivery'),
    
    path('registrar-cliente/', register_client, name='register_client'),
    path('sair/', logout_account, name='logout_account'),
    path('entrar/', login_account, name='login_account'),
    
    path('minha-conta/', my_account, name='my_account'),
    path('minha-conta/detalhe-compra-<int:pk>/', detail_buy, name='detail_buy'),

    path('pesquisar/', search, name='search'),
]

electro/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from stdimage.models import StdImageField
import uuid
from django.contrib.auth.models import User


STATUS = (
    ('Pedido Recebido', 'Pedido Recebido'),
    ('Pedido Processado', 'Pedido Processado'),
    ('Pedido a Caminho', 'Pedido a Caminho'),
    ('Pedido Entregue', 'Pedido Entregue'),
    ('Pedido Cancelado', 'Pedido Cancelado'),
)


def get_file_path(_instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return 'products/' + str(filename)


class Base(models.Model):
    created = models.DateField('Data de Criação', auto_now_add=True)
    modified = models.DateField('Data de Modificação', auto_now=True)
    active = models.BooleanField('Ativo', default=True)

    class Meta:
        abstract = True


class Client(Base):
    user = models.OneToOneField(User, verbose_name='Usuario', on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=100)
    address = models.CharField('Endereço', max_length=200)
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return self.name


class Category(Base):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Slug', unique=True)
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class Maker(Base):
    name = models.CharField('Nome', max_length=100)
    
    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __str__(self):
        return self.name


class Color(Base):
    name = models.CharField('Nome', max_length=100)
    code = models.CharField('Código', max_length=10)
    
    class Meta:
        verbose_name = 'Cor'
        verbose_name_plural = 'Cores'

    def __str__(self):
        return self.name


class Product(Base):
    name = models.CharField('Nome', max_length=100)
    detail = models.TextField('Detalhes')
    price = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    amount = models.IntegerField('Estoque')
    slug = models.SlugField('Slug', unique=True)
    image = StdImageField('Imagem', upload_to=get_file_path, variations={'thumb': {'width': 480, 'height': 480, 'crop': True}})
    views = models.PositiveIntegerField()

    category = models.ForeignKey('core.Category', verbose_name='Categoria', on_delete=models.CASCADE)
    maker = models.ForeignKey('core.Maker', verbose_name='Marca', on_delete=models.CASCADE)
    color = models.ForeignKey('core.Color', verbose_name='Cor', on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return self.name


class Cart(Base):
    client = models.ForeignKey(Client, verbose_name='Cliente', on_delete=models.SET_NULL, null=True, blank=True)
    delivery = models.DecimalField('Entrega', max_digits=8, decimal_places=2, blank=True, null=True)
    total = models.DecimalField('Total', max_digits=8, decimal_places=2)

    class Meta:
        verbose_name = 'Carrinho'
        verbose_name_plural = 'Carrinhos'

    def __str__(self):
        return 'Carrinho: ' + str(self.id)


class CartProduct(Base):
    cart = models.ForeignKey(Cart, verbose_name='Carrinho', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade')
    total = models.DecimalField('Total', max_digits=8, decimal_places=2)

    class Meta:
        verbose_name = 'Produto no Carrinho'
        verbose_name_plural = 'Produtos no Carrinho'

    def __str__(self):
        return 'Carrinho: ' + str(self.cart.id) + ', Produto no Carrinho: ' + str(self.id)


class Buy(Base):
    cart = models.OneToOneField(Cart, verbose_name='Carrinho', on_delete=models.CASCADE)
    recipient = models.CharField('Destinatário', max_length=200)
    email = models.EmailField('Email')
    address = models.CharField('Endereço', max_length=200)
    total = models.DecimalField('Total', max_digits=8, decimal_places=2)
    status = models.CharField('Status', max_length=50, choices=STATUS)
    
    class Meta:
        verbose_name = 'Compra'
        verbose_name_plural = 'Compras'

    def __str__(self):
        return 'Cliente: ' + str(self.cart.client) + ', Data: ' +  str(self.created)


class Favorite(Base):
    client = models.OneToOneField(Client, verbose_name='Cliente', on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField('Quantidade')
    
    class Meta:
        verbose_name = 'Favorito'
        verbose_name_plural = 'Favoritos'

    def __str__(self):
        return str(self.client)


class FavoriteProduct(Base):
    favorite = models.ForeignKey(Favorite, verbose_name='Favorito', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Produto', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Produto Favorito'
        verbose_name_plural = 'Produtos Favoritos'

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.core.paginator import Paginator
from datetime import datetime, timedelta

import urllib.request as urllib2
import http.cookiejar as cookielib
import  xml.etree
import xmltodict
import pprint
import json
import requests

from .models import *
from .forms import *


# Método que salva o usuário logado no carrinho de compra
def save_client(request):
    cart_id = request.session.get('cart_id')
    if cart_id:
        cart_obj = Cart.objects.get(id=cart_id)

        if request.user.is_authenticated and request.user.client:
            cart_obj.client = request.user.client
            cart_obj.save()


# Método que retorna os dados do link 
def file_get_contents(url):
    url = str(url).replace(" ", "+") # just in case, no space in url
    hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
           'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
           'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
           'Accept-Encoding': 'none',
           'Accept-Language': 'en-US,en;q=0.8',
           'Connection': 'keep-alive'}
    req = urllib2.Request(url, headers=hdr)
    try:
        page = urllib2.urlopen(req)
        return page.read()
    except urllib2.HTTPError as e:
        print(e.fp.read())
    return ''


# Exibe a quantidade de produtos no carrinho
def cart_quantity(request):
    cart_id = request.session.get('cart_id')
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = None
    return cart


# Exibe a quantidae de produtos nos favoritos
def favorites_quantity(request):
    if request.user.is_authenticated and request.user.client:
        client = request.user.client
    else:
        client = None
    return client


# Página principal do site
def index(request): 
    context = {
        'products': Product.objects.all(),
        'categories': Category.objects.all(),
        'colors': Color.objects.all(),
        'makers': Maker.objects.all(),

        'cart_product': CartProduct.objects.filter(cart=cart_quantity(request)),
        'favorite_product': FavoriteProduct.objects.filter(favorite__client=favorites_quantity(request)),
        
        # Seleciona os produtos adicionados em até cinco dias atrás
        'news': Product.objects.filter(created__gte=datetime.now() - timedelta(days=5)),
        'views': Product.objects.all().order_by('-views')[:7]
    }
    return render(request, 'index.html', context)

    
# Página de categorias do produtos
def categories(request):
    context = {
        'categories': Category.objects.all(), 

        'cart_product': CartProduct.objects.filter(cart=cart_quantity(request)),
        'favorite_product': FavoriteProduct.objects.filter(favorite__client=favorites_quantity(request)), 
    }
    return render(request, 'categories.html', context)


# Página de categorias do produtos
def category_product(request, slug):
    category = get_object_or_404(Category, slug=slug)

    context = {
        'category': category,
        'categories': Category.objects.all(),

        'cart_product': CartProduct.objects.filter(cart=cart_quantity(request)),
        'favorite_product': FavoriteProduct.objects.filter(favorite__client=favorites_quantity(request)),
    }
    return render(request, 'category_product.html', context)


# Página do produto
def product(request, slug):
    # Seleciona o produto através do slug
    product = get_object_or_404(Product, slug=slug)
    product.views += 1
    product.save()

    context = {
        'product': product,
        'categories': Category.objects.all(),
        'views': Product.objects.all().order_by('-views')[:7],

        'cart_product': CartProduct.objects.filter(cart=cart_quantity(request)),
        'favorite_product': FavoriteProduct.objects.filter(favorite__client=favorites_quantity(request)),
    }
    return render(request, 'product.html', context)


# Método que cria e atualiza o carrrinho de compras 
def favorite(request, id):
    if request.user.is_authenticated and request.user.client:
        pass
    else:
        return redirect(f'/entrar/?next=/favoritos-{id}')

    favorite = Favorite.objects.get(client=request.user.client)
    product = get_object_or_404(Product, id=id)
    product_in_favorite = favorite.favoriteproduct_set.filter(product=product)

    # Se o produto já existe no carrinho 
    if product_in_favorite.exists():
        messages.error(request, 'Produto já estava adicinado aos favoritos')      

    # Se o produto não existe no carrinho 
    else:
        favoriteproduct = FavoriteProduct.objects.create(favorite=favorite, product=product)
        favoriteproduct.save()
        messages.error(request, 'Produto adicinado aos favoritos')

    return redirect('core:favorites')


# Método que cria e atualiza o carrrinho de compras 
def cart(request, id):
    product = get_object_or_404(Product, id=id)
    
    # Recupera a sessão ou atribui 'None', caso ela não exista
    cart_id = request.session.get('cart_id', None)
    
    # Se a sessão existe
    if cart_id:

        # Salva o usuário logado no carrinho de compras
        save_client(request)

        # Pega o carrinho e filtra pelo produto selecionado
        cart_obj = Cart.objects.get(id=cart_id)
        product_in_cart = cart_obj.cartproduct_set.filter(product=product)

        # Se o produto já existe no carrinho 
        if product_in_cart.exists():
            cartproduct = product_in_cart.last()
            cartproduct.quantity += 1
            cartproduct.total += product.price
            cartproduct.save()

            cart_obj.total += product.price
            cart_obj.save()
            

        # Se o produto não existe no carrinho 
        else:
            cartproduct = CartProduct.objects.create(
                cart = cart_obj,
                product = product,
                quantity = 1,
                total = product.price
            )

            cart_obj.total += product.price
            cart_obj.save()
            
    # Se a sessão não existe
    else:
        cart_obj = Cart.objects.create(total = 0)
        request.session['cart_id'] = cart_obj.id

        cartproduct = CartProduct.objects.create(
                cart = cart_obj,
                product = product,
                quantity = 1,
                total = product.price
        )

        cart_obj.total += product.price
        cart_obj.save()

        # Salva o usuário logado no carrinho de compras
        save_client(request)

    return redirect('core:my_cart')


# Página que exibe os produtos no carrinho de compras
def my_cart(request):
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)

        # Salva o usuário logado no carrinho de compras
        save_client(request)
    else:
        cart = None

    context = {
        'cart': cart,
        'categories': Category.objects.all(),

        'cart_product': CartProduct.objects.filter(cart=cart_quantity(request)),
        'favorite_product': FavoriteProduct.objects.filter(favorite__client=favorites_quantity(request)),
    }
    return render(request, 'my_cart.html', context)


# Método que realiza alterações no carrinho de compras
def edit_cart(request, id):
    action = request.GET.get('action')
    cart_product = CartProduct.objects.get(id=id)
    cart = cart_product.cart

    # Salva o usuário logado no carrinho de compras
    save_client(request)

    if action == 'inc':
        cart_product.quantity += 1
        cart_product.total += cart_product.product.price
        cart_product.save()

        cart.total += cart_product.product.price
        cart.save()

    elif action == 'dec':
        cart_product.quantity -= 1
        cart_product.total -= cart_product.product.price
        cart_product.save()

        cart.total -= cart_product.product.price
        cart.save()

        if cart_product.total == 0:
            cart_product.delete()

    elif action == 'del':
        cart.total -= cart_product.total
        cart.save()

        cart_product.delete()

    else:
        pass
    
    return redirect('core:my_cart')


# Método que apaga o carrinho
def remove_cart(request):
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
        cart.cartproduct_set.all().delete()
        cart.total = 0
        cart.save()

    return redirect('core:my_cart')


# Método que exibe a página de compra ou salva seus dados no banco
def buy(request):
    if str(request.method) == 'POST':
        form = BuyModelForm(request.POST)
        cart_id = request.session.get('cart_id')

        if cart_id:
            cart = Cart.objects.get(id=cart_id)

            form.instance.cart = cart
            form.instance.total = cart.total
            form.instance.status = "Pedido Recebido"

            if form.is_valid():
                form.save()
                del request.session['cart_id']

                messages.success(request, 'Compra efetuada com sucesso!')
                return redirect('core:index')

            else:
                messages.error(request, 'Erro com os dados do formulário')
                return redirect('core:index')
                       
        else:
            messages.error(request, 'Erro ao efetuar a compra!')
            return redirect('core:index')

    else:
        # Salva o usuário logado no carrinho de compras
        save_client(request)
        
        if request.user.is_authenticated and request.user.client:
            pass
        else:
            return redirect('/entrar/?next=/comprar')

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>{% block title %}{% endblock %}</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> (79) 99999 - 9999</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> Centro, Aracaju - SE</a></li>
					</ul>
					<ul class="header-links pull-right">
						
						{% if request.user.client %}
							<li><a href="{% url 'core:my_account' %}"><i class="fa fa-user-o"></i> Minha Conta</a></li>
							<li><a href="{% url 'core:logout_account' %}"><i class="fa fa-user-o"></i> Sair</a></li>
						{% else %}
							<li><a href="{% url 'core:login_account' %}"><i class="fa fa-user-o"></i> Entrar</a></li>
						{% endif %}
						
						
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="#" class="logo">
									<img src="./img/logo.png" alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form action="{% url 'core:search' %}" method="GET">
									<select class="input-select" name="category">
										<option value="Todos">Todos</option>
										{% if categories %}
											{% for category in categories %}
												<option value="{{ category.slug }}">{{ category }}</option>
											{% endfor %}
										{% endif %}
									</select>
									<input type="text" class="input" name="search" placeholder="Pesquisar Aqui" required>
									<button class="search-btn">Pesquisar</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<div>
									<a href="{% url 'core:favorites' %}">
										<i class="fa fa-heart-o"></i>
										<span>Favoritos</span>
										<div class="qty">
											{% if favorite_product %}
												{{ favorite_product.count }}
											{% else %}
												0
											{% endif %}
										</div>
									</a>
								</div>
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a href="{% url 'core:my_cart' %}">
										<i class="fa fa-shopping-cart"></i>
										<span>Carrinho</span>
										<div class="qty">
											{% if cart_product %}
												{{ cart_product.count }}
											{% else %}
												0
											{% endif %}
										</div>
											
									</a>
									
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="{% url 'core:index' %}">Início</a></li>
						<li><a href="{% url 'core:categories' %}">Categorias</a></li>
						{% if categories %}
							{% for category in categories %}
								<li><a href="{% url 'core:category_product' category.slug %}">{{ category }}</a></li>
							{% endfor %}
						{% endif %}
						
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		

        {% block content %}

        {% endblock %}


        <!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

core/templates/cart.html
cart

{{product.name}}

{{cartproduct.total}}

core/templates/my_cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Meu Carrinho{% endblock %}

{% block content %}

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            {% if cart.total == 0 or cart == None %}

                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title text-center">
                        <br/><br/><br/><br/><br/><br/>
                        <h3 class="title">Carrinho Vazio! ;(</h3>
                        <br/><br/><br/><br/><br/><br/>
                    </div>
                </div>
                <!-- /section title -->

            {% else %}

                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title text-center">
                        <h3 class="title">Meu Carrinho</h3>
                    </div>
                </div>
                <!-- /section title -->

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Código</th>
                        <th scope="col">Produto</th>
                        <th scope="col">Preço</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Subtotal</th>
                        <th scope="col">Ação</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for prod in cart.cartproduct_set.all %}
                        <tr>
                            <th scope="row">{{prod.id}}</th>
                            <td>{{prod.product}}</td>
                            <td>{{prod.product.price}}</td>
                            <td>{{prod.quantity}}</td>
                            <td>{{prod.total}}</td>
                            <td>
                                <a href="{% url 'core:edit_cart' prod.id %}?action=inc"><button type="button" class="btn btn-success"> + </button></a>
                                <a href="{% url 'core:edit_cart' prod.id %}?action=dec"><button type="button" class="btn btn-warning"> - </button></a>
                                <a href="{% url 'core:edit_cart' prod.id %}?action=del"><button type="button" class="btn btn-danger"> x </button></a>
                            </td>
                            
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

                <h4>Total: {{cart.total}}</h4>
                <a href="{% url 'core:remove_cart' %}"><button type="button" class="btn btn-danger"> Limpar Carrinho </button></a>
                <a href="{% url 'core:buy' %}"><button type="button" class="btn btn-success"> Realizar Compra </button></a>
            
            {% endif %}
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->

{% endblock %}